[package]
name = "fb-parser"
version = "0.1.0"
authors = ["Javier L. <135663+xleyba@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4.10"
structopt = "0.3.5"